# Partie 1 – Series

In [29]:
import numpy as np
import pandas as pd

In [2]:
temperatures = pd.Series([22.5, 24.0, 21.8, 25.3])
print(temperatures)

0    22.5
1    24.0
2    21.8
3    25.3
dtype: float64

In [3]:
print(temperatures.index)

RangeIndex(start=0, stop=4, step=1)

In [4]:
print(temperatures.iloc[0])

22.5

In [5]:
print(temperatures.iloc[-1])

25.3

In [6]:
heures = ["12h", "13h", "14h", "15h"]
temp_series1 = pd.Series([22.5, 24.0, 21.8, 25.3], index=heures)

temp_dict = {"12h": 22.5, "13h": 24.0, "14h": 21.8, "15h": 25.3}
temp_series2 = pd.Series(temp_dict)

print("Méthode 1 :\n", temp_series1)
print("\nMéthode 2 :\n", temp_series2)

Méthode 1 :
 12h    22.5
13h    24.0
14h    21.8
15h    25.3
dtype: float64

Méthode 2 :
 12h    22.5
13h    24.0
14h    21.8
15h    25.3
dtype: float64

In [7]:
print(temp_series1[["12h", "15h"]])

12h    22.5
15h    25.3
dtype: float64

# Partie 2 – DataFrame

In [8]:
data = {
    "capteur": ["C001", "C002", "C003"],
    "temperature": [24.5, 25.1, 26.3],
    "humidite": [65, 67, 70]
}

df_test=pd.DataFrame(data)

In [8]:
df=pd.read_csv(r"C:\Users\odc\Desktop\Lamine\atelier_pandas_iot\data\mesures_capteurs.csv")
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 4:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 1:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 4:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 6:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

In [9]:
df.shape

(605, 9)

# Partie 3 – Exploration

In [11]:
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 4:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 1:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 4:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 6:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

In [10]:
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 4:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 1:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 4:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 6:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

In [12]:
df.tail()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 6:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 3:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 6:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

In [14]:
df.shape[0]

605

In [15]:
df.shape[1]

9

In [ ]:
df.columns

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite', 'pression', 'consommation', 'etat'],
      dtype='str')

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    str
 1   date_heure    605 non-null    str
 2   id_capteur    605 non-null    str
 3   batiment      605 non-null    str
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    str
dtypes: float64(4), str(5)
memory usage: 42.7 KB

In [20]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
temperature,599.0,24.878314,4.059576,-18.50,22.5700,24.860,27.2750,58.70
humidite,600.0,64.926200,10.769050,28.52,58.1725,65.375,71.6150,145.00
pression,600.0,1012.221900,10.599042,850.00,1006.7900,1012.855,1017.8275,1038.43
consommation,600.0,208.675417,72.243567,18.12,160.1775,206.150,254.1275,875.00

# Partie 4 – Sélection

In [21]:
df.temperature

0      25.46
1      24.00
2      25.82
3      28.23
4      20.58
       ...
600    23.67
601    24.34
602    23.73
603    24.83
604    17.02
Name: temperature, Length: 605, dtype: float64

In [22]:
df[["temperature","humidite","consommation","pression"]]

     temperature  humidite  consommation  pression
0          25.46     58.06        287.28   1008.95
1          24.00     79.73        116.20    993.39
2          25.82     54.47        288.50   1010.32
3          28.23     69.39        136.65   1019.62
4          20.58     53.80        182.62   1016.58
..           ...       ...           ...       ...
600        23.67     60.28        282.36   1015.11
601        24.34     61.42        357.43   1019.43
602        23.73     63.49        152.79   1016.46
603        24.83     79.77        170.97   1017.05
604        17.02     52.04         44.99   1001.14

[605 rows x 4 columns]

In [24]:
df.loc[:4,:]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 4:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 1:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 4:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 6:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

In [ ]:
#les 5 premières lignes et les 4 premières colonnes avec iloc
df.iloc[:5,:4]

  id_mesure           date_heure id_capteur batiment
0     M0413   2026-01-22 4:00:00       C005     B002
1     M0290   2026-01-17 1:00:00       C002     B001
2     M0077   2026-01-08 4:00:00       C005     B002
3     M0079   2026-01-08 6:00:00       C007     B003
4     M0183  2026-01-12 14:00:00       C003     B001

# Partie 5 – Manipulation des colonnes

In [26]:
df

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 4:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 1:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 4:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 6:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
...,...,...,...,...,...,...,...,...,...
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 6:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 3:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 6:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

In [27]:
df["temperature_fahrenheit"] = df["temperature"] * 1.8 + 32

In [30]:
df["niveau_temperature"] = np.where(df["temperature"] > 30, "Élevée", "Normale")

In [32]:
df.rename(columns={"humidite":"humidite_relative"})

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,temperature_fahrenheit,niveau_temperature
0,M0413,2026-01-22 4:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,77.828,Normale
1,M0290,2026-01-17 1:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,75.200,Normale
2,M0077,2026-01-08 4:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,78.476,Normale
3,M0079,2026-01-08 6:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK,82.814,Normale
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK,69.044,Normale
...,...,...,...,...,...,...,...,...,...,...,...
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK,74.606,Normale
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK,75.812,Normale
602,M0271,2026-01-16 6:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK,74.714,Normale
603,M0436,2026-01-23 3:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK,76.694,Normale
604,M0103,2026-01-09 6:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK,62.636,Normale

In [33]:
df = df.drop(columns=["temperature_fahrenheit"])

# Partie 6 – Filtrage

In [35]:
df_temp_sup_30 = df[df["temperature"] > 30]

In [36]:
df_filtre = df[(df["temperature"] > 30) & (df["humidite"] > 70)]

# Partie 7 : Tri

In [39]:
df_trie1=df.sort_values(by="temperature",ascending=True)
df_trie1.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat,niveau_temperature
487,M0538,2026-01-27 9:00:00,C010,B004,-18.50,66.27,1012.49,312.92,ERREUR,Normale
245,M0127,2026-01-10 6:00:00,C007,B003,14.11,145.00,1032.36,169.57,ERREUR,Normale
258,M0223,2026-01-14 6:00:00,C007,B003,15.49,47.96,1006.34,124.90,OK,Normale
249,M0175,2026-01-12 6:00:00,C007,B003,16.04,55.36,1005.68,140.95,OK,Normale
59,M0146,2026-01-11 1:00:00,C002,B001,16.77,53.44,1010.65,131.75,OK,Normale

In [40]:
df_trie2=df.sort_values(by="temperature",ascending=False)
df_trie2.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat,niveau_temperature
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR,Élevée
43,M0575,2026-01-28 22:00:00,C011,B004,34.72,57.50,1008.94,266.22,ALERTE,Élevée
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Élevée
211,M0370,2026-01-20 9:00:00,C010,B004,33.29,50.43,1009.87,356.76,ALERTE,Élevée
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Élevée

In [41]:
df_trie2.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat,niveau_temperature
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR,Élevée
43,M0575,2026-01-28 22:00:00,C011,B004,34.72,57.50,1008.94,266.22,ALERTE,Élevée
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Élevée
211,M0370,2026-01-20 9:00:00,C010,B004,33.29,50.43,1009.87,356.76,ALERTE,Élevée
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Élevée
118,M0365,2026-01-20 4:00:00,C005,B002,32.90,65.91,1027.28,246.08,ALERTE,Élevée
520,M0063,2026-01-07 14:00:00,C003,B001,32.72,53.28,1010.05,195.37,ALERTE,Élevée
438,M0558,2026-01-28 5:00:00,C006,B002,32.56,67.77,1016.88,181.51,ALERTE,Élevée
47,M0082,2026-01-08 9:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE,Élevée
169,M0546,2026-01-27 17:00:00,C006,B002,32.36,67.34,998.10,184.89,ALERTE,Élevée

In [43]:
df.sort_values(by=["batiment", "temperature"], 
    ascending=[True, False]).head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat,niveau_temperature
520,M0063,2026-01-07 14:00:00,C003,B001,32.72,53.28,1010.05,195.37,ALERTE,Élevée
447,M0170,2026-01-12 1:00:00,C002,B001,31.15,69.20,1016.10,172.49,OK,Élevée
224,M0303,2026-01-17 14:00:00,C003,B001,30.84,67.98,1020.09,157.99,OK,Élevée
500,M0062,2026-01-07 13:00:00,C002,B001,30.39,52.13,1004.23,262.66,OK,Élevée
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK,Normale