# Partie 1 – Series

In [1]:
import pandas as pd

In [2]:
temperatures = pd.Series([22.5, 24.0, 21.8, 25.3])
print(temperatures)

0    22.5
1    24.0
2    21.8
3    25.3
dtype: float64

In [3]:
print(temperatures.index)

RangeIndex(start=0, stop=4, step=1)

In [4]:
print(temperatures.iloc[0])

22.5

In [5]:
print(temperatures.iloc[-1])

25.3

In [6]:
heures = ["12h", "13h", "14h", "15h"]
temp_series1 = pd.Series([22.5, 24.0, 21.8, 25.3], index=heures)

temp_dict = {"12h": 22.5, "13h": 24.0, "14h": 21.8, "15h": 25.3}
temp_series2 = pd.Series(temp_dict)

print("Méthode 1 :\n", temp_series1)
print("\nMéthode 2 :\n", temp_series2)

Méthode 1 :
 12h    22.5
13h    24.0
14h    21.8
15h    25.3
dtype: float64

Méthode 2 :
 12h    22.5
13h    24.0
14h    21.8
15h    25.3
dtype: float64

In [7]:
print(temp_series1[["12h", "15h"]])

12h    22.5
15h    25.3
dtype: float64

# Partie 2 – DataFrame

In [8]:
data = {
    "capteur": ["C001", "C002", "C003"],
    "temperature": [24.5, 25.1, 26.3],
    "humidite": [65, 67, 70]
}

df_test=pd.DataFrame(data)

In [8]:
df=pd.read_csv(r"C:\Users\odc\Desktop\Lamine\atelier_pandas_iot\data\mesures_capteurs.csv")
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 4:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 1:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 4:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 6:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

In [9]:
df.shape

(605, 9)

# Partie 3 – Exploration

In [11]:
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 4:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 1:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 4:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 6:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

In [10]:
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 4:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 1:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 4:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 6:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

In [12]:
df.tail()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 6:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 3:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 6:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

In [14]:
df.shape[0]

605

In [15]:
df.shape[1]

9

In [ ]:
df.columns

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite', 'pression', 'consommation', 'etat'],
      dtype='str')

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    str
 1   date_heure    605 non-null    str
 2   id_capteur    605 non-null    str
 3   batiment      605 non-null    str
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    str
dtypes: float64(4), str(5)
memory usage: 42.7 KB

In [20]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
temperature,599.0,24.878314,4.059576,-18.50,22.5700,24.860,27.2750,58.70
humidite,600.0,64.926200,10.769050,28.52,58.1725,65.375,71.6150,145.00
pression,600.0,1012.221900,10.599042,850.00,1006.7900,1012.855,1017.8275,1038.43
consommation,600.0,208.675417,72.243567,18.12,160.1775,206.150,254.1275,875.00